#!/usr/bin/env python

import sys,os
from os.path import dirname, join, pardir

try:
	from radiotray import radiotray_runner
except ImportError:
	basedir = os.path.dirname(os.path.realpath(__file__))
	workdir = join(basedir,'src')
	sys.path.insert(0, workdir)
	os.chdir(workdir)
	import radiotray_runner 
	
radiotray_runner.main(sys.argv[1:])
